version: '3'
services:
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=asdf
    ports:
      - "5432:5432"
    volumes:
      - ./src/schema.sql:/docker-entrypoint-initdb.d/0_schema.sql
    command: postgres -c 'max_wal_size=2GB'
